// Generated by packtype (https://github.com/Intuity/packtype)
// Source file : /Users/stuartalldred/Code/rheon/.venv/lib/python3.13/site-packages/packtype/wrap.py
//

/* verilator lint_off UNUSEDPARAM */

package rheon_pkg;

// =============================================================================
// Imports
// =============================================================================


// =============================================================================
// Constants
// =============================================================================

// XLEN
localparam XLEN = 'h00000040;
// INSTR_WIDTH
localparam INSTR_WIDTH = 'h00000020;
// ADDR_WIDTH
localparam ADDR_WIDTH = 'h00000040;
// FETCH_LINE_WORDS
localparam FETCH_LINE_WORDS = 'h00000004;
// GPR_COUNT
localparam GPR_COUNT = 'h00000020;
// PIPELINE_STAGES
localparam PIPELINE_STAGES = 'h00000004;

// =============================================================================
// Typedefs
// =============================================================================


// =============================================================================
// Enumerations
// =============================================================================

// =============================================================================
// Structs and Unions
// =============================================================================


endpackage : rheon_pkg

/* verilator lint_on UNUSEDPARAM */
